FROM node:14-stretch-slim as build
WORKDIR /app
COPY . /app
RUN npm install && npm run build

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html


FROM stefanscherer/node-windows:latest as build
WORKDIR /app
COPY . /app
RUN npm install && npm run build
FROM nginx:stable-alpine
COPY --from=build app/build /usr/share/nginx/html
