   #test
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: duyenle/react-docker
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  test-build-docker-cicd:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
